name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions: read-all

jobs:
  task6:
    strategy:
      fail-fast: false

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./task6

    steps:
      - uses: actions/checkout@v4

      - uses: erlef/setup-beam@v1
        with:
          otp-version: "27.1.2"
          gleam-version: "1.12.0"
          rebar3-version: "3"

      - run: gleam deps download
      - run: gleam test
      - run: gleam format --check src test

  task25:
    strategy:
      fail-fast: false

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./task25

    steps:
      - uses: actions/checkout@v4

      - uses: erlef/setup-beam@v1
        with:
          otp-version: "27.1.2"
          gleam-version: "1.12.0"
          rebar3-version: "3"

      - run: gleam deps download
      - run: gleam test
      - run: gleam format --check src test
